apiVersion: v1
kind: Service
metadata:
        name: swagger-service
spec:
        selector:
                app: swagger
        ports:
                - port: 80
                  targetPort: 8080
                  nodePort: 30000
        type: NodePort
