apiVersion: v1
kind: Service
metadata:
        name: nginx-service
spec:
        selector:
                app: nginx #Alvo do service
        ports:
                - port: 80
                  nodePort: 30000
        type: NodePort

